#' Run K-fold cross-validation analysis (CVA)
#'
#' This function runs a K-fold cross-validation analysis (CVA) using blupf90 modules.
#'
#' This function sets up and runs a K-fold cross-validation analysis (CVA) using blupf90+ and predictf90.
#' The function run_renumf90 needs to be used beforehand to process a .par file created by the user.
#' This function calculates 2 accuracy estimates: correlation between raw phenotypes and ebvs divided by the square-root of narrow sense heritabilty and correlation between corrected phenotypes and ebvs along with bias estimations calculated as the regression of the phenotypes on the ebvs.
#'
#' @param path_2_execs path to a folder that holds all blupf90 executables that ill be used (blupf90+,predictf90). This field should be in quotes "".
#' @param missing_value_code code used in the .par file after OPTION MISSING to indicate missing phenotype, if this option is no use, this value must be 0.
#' @param random_effect_col Column where random effects are located, found under RANDOM_GROUP in the renf90.par file.
#' @param h2 estimate of narow-sense heritabilty.This value is use to calculate accuracy of ebvs
#' @param num_runs Number of independent cross-valdation runs to be performed.
#' @param num_folds Number of folds to be generated within each independent run.
#' @param output_table_name Name of the final tab-separated out-up file. This field should be in quotes "".
#' @param renf90_ped_name Name of pedigree file generated by renumf90. This field should be in quotes "".
#' @return a tab-separated file that includes accuracy and bias estimates of ebvs.
#' @import dplyr
#' @examples
#' ## Example for a CVA with 5 independent runs dividing the data in 10 folds.
#'
#'
#' # bf90_cv(path_2_execs = "/Users/johndoe/Desktop/bf90_execs/",
#' #      missing_value_code = -999,
#' #      random_effect_col= 3,
#' #      h2 = 0.5,
#' #      num_runs = 5,
#' #      num_folds = 10,
#' #      output_table_name = "example_run",
#'  #     renf90_ped_name = "renadd03.ped")
#'
#' #The function will output the file "example_run" with a layout:
#' # Metric Run Value
#' # y-ebv_correlation run 1 0.038
#' # y-ebv_correlation run 2 0.053
#' # y-ebv_correlation run 3 0.112
#' # y-ebv_correlation run 4 0.075
#' # y-ebv_correlation run 5 0.089
#' # y*-ebv_correlation run 1 0.947
#' # y*-ebv_correlation run 2 0.964
#' # y*-ebv_correlation run 3 0.893
#' # y*-ebv_correlation run 4 0.883
#' # y*-ebv_correlation run 5 0.939
#' # bias run 1 0.085
#' # bias run 2 0.117
#' # bias run 3 0.262
#' # bias run 4 0.164
#' # bias run 5 0.189
#' # y-ebv_average_corr  0.074
#' # y*-ebv_accuracy  0.925
#' # y_corrected_accuracy (yraw_average_corr/sqrt(h2))  0.105
#' # verage_bias  0.163
#'
#' @export
bf90_cv <- function(path_2_execs, missing_value_code, random_effect_col, h2, num_runs, num_folds, output_table_name, renf90_ped_name) {
  #set seed for reproducibility
  set.seed(101919)

  #define working directory
  wd_path <- getwd()
  #set base_path for results folder
  base_path <- paste0(getwd(), "/bf90_cv_results/")

  # Function to run commands on the terminal and log output
  mac_terminal_command <- function(command, logfile) {
    system(paste(command, "2>&1 | tee -a", logfile))
  }

  # Run BF90 programs for the whole dataset
  mac_terminal_command(command = paste0(path_2_execs, "blupf90+ renf90.par"), logfile = "BLUP_cv.log")
  mac_terminal_command(command = paste0(path_2_execs, "predictf90 renf90.par"), logfile = "predict_cv.log")

  # Prepare files for each BLUP run
  renf90 <- base::readLines("renf90.par")
  ped_file <- renf90_ped_name
  fields_file <- base::readLines("renf90.fields")
  inb_file <- base::readLines("renf90.inb")
  tables_file <- base::readLines("renf90.tables")

  # Read and preprocess the phenotype data
  bf90_phenos <- utils::read.table("renf90.dat", sep = " ", header = FALSE) %>%
    dplyr::select(-1)

  # Shuffle the data and create folds
  data_shuffled <- lapply(1:num_runs, function(x) bf90_phenos[sample(base::nrow(bf90_phenos)), ] %>%
                            dplyr::select((random_effect_col + 1)))
  create_folds <- function(data) {
    n <- base::nrow(data)
    fold_size <- n %/% num_folds
    folds <- vector("list", num_folds)
    for (i in 1:num_folds) {
      start_index <- (i - 1) * fold_size + 1
      end_index <- if (i == num_folds) n else i * fold_size
      folds[[i]] <- data[start_index:end_index, ]
    }
    folds
  }
  folds <- lapply(data_shuffled, create_folds)

  # Function to mutate phenotypes to missing value for given folds
  mutate_folds <- function(phenos, folds) {
    lapply(1:num_folds, function(i) {
      phenos %>%
        dplyr::mutate(V2 = ifelse(V5 %in% folds[[i]], missing_value_code, V2))
    })
  }
  mutated_data <- lapply(folds, function(f) mutate_folds(bf90_phenos, f))

  # Create cross-validation datasets
  for (run in 1:num_runs) {
    for (fold in 1:num_folds) {
      file_name <- sprintf("renf90_run%d_fold%d.dat", run, fold)
      data_frame <- mutated_data[[run]][[fold]]
      utils::write.table(data_frame, file = file_name, sep = " ", row.names = FALSE, col.names = FALSE, quote = FALSE)

      folder_path <- sprintf("bf90_cv_results/run%d/fold%d", run, fold)
      if (!file.exists(folder_path)) {
        dir.create(folder_path, recursive = TRUE)
      }
      file.rename(file_name, file.path(folder_path, file_name))
    }
  }

  for (run in 1:num_runs) {
    for (fold in 1:num_folds) {
      dir_path <- sprintf("bf90_cv_results/run%d/fold%d", run, fold)
      modified_content <- gsub("renf90.dat", sprintf("renf90_run%d_fold%d.dat", run, fold), renf90)
      base::writeLines(modified_content, file.path(dir_path, sprintf("renf90_run%d_fold%d.par", run, fold)))

      file.copy(renf90_ped_name, file.path(dir_path, renf90_ped_name))
      file.copy("renf90.fields", file.path(dir_path, "renf90.fields"))
      file.copy("renf90.inb", file.path(dir_path, "renf90.inb"))
      file.copy("renf90.tables", file.path(dir_path, "renf90.tables"))
    }
  }

  # Run BLUPf90+ for each fold and collect EBVs
  ebvs_for_cv_runs <- list()
  for (run in 1:num_runs) {
    ebvs_for_cv_list <- list()
    for (fold in 1:num_folds) {
      setwd(file.path(base_path, sprintf("run%d/fold%d", run, fold)))
      command <- paste0(path_2_execs, "blupf90+ ", sprintf("renf90_run%d_fold%d.par", run, fold))
      logfile <- sprintf("blup_fold%d_run%d.log", fold, run)
      mac_terminal_command(command = command, logfile = logfile)

      data_file <- sprintf("renf90_run%d_fold%d.dat", run, fold)
      masked_ids <- utils::read.table(data_file) %>%
        dplyr::filter(V1 == missing_value_code) %>%
        dplyr::select(4) %>%
        base::unlist()

      ebvs_for_cv <- utils::read.table("solutions", header = FALSE, skip = 1) %>%
        dplyr::filter(V2 == random_effect_col & V3 %in% masked_ids) %>%
        dplyr::select(3, 4)

      ebvs_for_cv_list[[fold]] <- ebvs_for_cv
      utils::write.table(ebvs_for_cv, file = sprintf("ebvs_for_cv_run%d_fold%d.dat", run, fold), row.names = FALSE, col.names = TRUE, quote = FALSE)
      setwd(wd_path)
    }
    ebvs_for_cv_runs[[sprintf("ebvs_for_cv_run%d", run)]] <- do.call(base::rbind, ebvs_for_cv_list)
  }

  # Calculate correlations and bias
  corrected_phenos <- utils::read.table("yhat_residual", header = FALSE) %>% dplyr::select(1, 2)
  raw_phenos <- utils::read.table("renf90.dat") %>% dplyr::select(4, 1)

  ystar_correlations <- numeric(num_runs)
  yraw_correlations <- numeric(num_runs)
  yraw_list <- vector("list", num_runs)
  coefficients_list <- vector("list", num_runs)
  bias_list <- numeric(num_runs)

  for (i in 1:num_runs) {
    ystar <- dplyr::inner_join(ebvs_for_cv_runs[[sprintf("ebvs_for_cv_run%d", i)]], corrected_phenos, by = c("V3" = "V1"))
    ystar_correlations[i] <- stats::cor(ystar$V4, ystar$V2)

    yraw <- dplyr::inner_join(ebvs_for_cv_runs[[sprintf("ebvs_for_cv_run%d", i)]], raw_phenos, by = c("V3" = "V4"))
    yraw_correlations[i] <- stats::cor(yraw$V4, yraw$V1)
    yraw_list[[i]] <- yraw

    model <- stats::lm(V1 ~ V4, data = yraw_list[[i]])
    coefficients_list[[i]] <- stats::coefficients(model)
    bias_list[i] <- stats::coefficients(model)["V4"]
  }

  ystar_accuracy <- round(base::mean(ystar_correlations), 3)
  yraw_average_corr <- round(base::mean(yraw_correlations), 3)
  yraw_accuracy <- round(yraw_average_corr / sqrt(h2), 3)
  average_bias <- round(base::mean(bias_list), 3)

  data <- data.frame(
    Metric = c(rep("y-ebv_correlation", num_runs), rep("y*-ebv_correlation", num_runs), rep("bias", num_runs), "y-ebv_average_corr", "y*-ebv_accuracy", "y_corrected_accuracy (yraw_average_corr/sqrt(h2))", "average_bias"),
    Run = c(paste("run", 1:num_runs), paste("run", 1:num_runs), paste("run", 1:num_runs), "", "", "", ""),
    Value = round(c(y-ebv_correlations, ystar_correlations, bias_list, yraw_average_corr, ystar_accuracy, yraw_accuracy, average_bias), 3)
  )
  print(paste0("****Accuracy and bias table****"))

  utils::write.table(data, file = output_table_name, row.names = FALSE, quote = FALSE)

  print(data)
}
