#' Run K-fold cross-validation analysis (CVA)
#'
#' This function runs a K-fold cross-validation analysis (CVA) using blupf90 modules.
#'
#' This function sets up and runs a K-fold cross-validation analysis (CVA) using blupf90+ and predictf90.
#' The function run_renumf90 needs to be used beforehand to process a .par file created by the user.
#' This function calculates 2 accuracy estimates: correlation between raw phenotypes and ebvs divided by the square-root of narrow sense heritabilty and correlation between corrected phenotypes and ebvs along with bias estimations calculated as the regression of the phenotypes on the ebvs.
#'
#' @param missing_value_code code used in the .par file after OPTION MISSING to indicate missing phenotype, if this option is no use, this value must be 0.
#' @param random_effect_col Column where random effect is located, found under RANDOM_GROUP in the renf90.par file.
#' @param h2 estimate of narrow-sense heritabilty.This value is use to calculate accuracy of ebvs
#' @param num_runs Number of independent cross-validation runs to be performed.
#' @param num_folds Number of folds to be generated within each independent run.
#' @param output_table_name Name of the final tab-separated out-up file. This field should be in quotes "".
#' @param renf90_ped_name Name of pedigree file generated by renumf90. This field should be in quotes "".
#' @param snp_file_name the name of the genotype file to be used. If use, this field should be in quotes"". Default for the function is no genotype file.
#' @param path_2_execs path to a folder that holds all blupf90 executables that ill be used (blupf90+,predictf90). This field should be in quotes "".
#' @param input_files_dir directory containing files renf90.par renf90.fields renf90.inb renf90.tables renf90.dat
#' @param output_files_dir path to directory to store the output files
#' @param seed set seed for the stochastic process
#' @param verbose logical defining if information will be printed on the console
#'
#' @return a tab-separated file that includes accuracy and bias estimates of ebvs.
#' @import dplyr
#' @examples
#' ## Example for a CVA with 5 independent runs dividing the data in 10 folds.
#'
#'
#' # bf90_cv(path_2_execs = "/Users/johndoe/Desktop/bf90_execs/",
#' #      missing_value_code = -999,
#' #      random_effect_col= 3,
#' #      h2 = 0.5,
#' #      num_runs = 5,
#' #      num_folds = 10,
#' #      output_table_name = "example_run",
#' #     renf90_ped_name = "renadd03.ped",
#' #     snp_file_name = "my_genos.geno" )
#'
#'
#' @export
bf90_cv <- function(missing_value_code = -999,
                    random_effect_col = 3,
                    h2 = 0.5,
                    num_runs = 5,
                    num_folds = 10,
                    path_2_execs = ".",
                    input_files_dir = ".",
                    output_files_dir = ".",
                    output_table_name = NULL,
                    renf90_ped_name="renadd03.ped",
                    snp_file_name = NULL,
                    seed = 101919,
                    verbose = TRUE) {


  #check id pedigree and genotype file are present
  if (!file.exists(renf90_ped_name)) {
    stop("Parameter file not found at: ", renf90_ped_name)
  }
  renf90_ped_name <- normalizePath(renf90_ped_name)

  input_files_dir <- normalizePath(input_files_dir)

  if (!file.exists(file.path(input_files_dir,"renf90.par"))) stop("File 'renf90.par' not found at: ", input_files_dir)
  if (!file.exists(file.path(input_files_dir,"renf90.inb"))) stop("File 'renf90.inb' not found at: ", input_files_dir)
  if (!file.exists(file.path(input_files_dir,"renf90.fields"))) stop("File 'renf90.fields' not found at: ", input_files_dir)
  if (!file.exists(file.path(input_files_dir,"renf90.tables"))) stop("File 'renf90.tables' not found at: ", input_files_dir)
  if (!file.exists(file.path(input_files_dir,"renf90.dat"))) stop("File 'renf90.dat' not found at: ", input_files_dir)

  if (!is.null(snp_file_name)) {
    if (!file.exists(snp_file_name)) {
      stop("Parameter file not found at:", snp_file_name)
      snp_file_name <- normalizePath(snp_file_name)
    }
  }

  if(is.null(output_table_name)) stop("Define output table name.")

  if (!file.exists(renf90_ped_name)) {
    stop("Parameter file not found at: ", renf90_ped_name)
  }

  # set seed for reproducibility
  base::set.seed(seed)


  # Checks
  output_files_dir <- normalizePath(output_files_dir)
  if(file.exists(output_files_dir)){
    check_files <- list.files(output_files_dir)
    if(length(check_files) > 0) warning(paste("Directory", output_files_dir, "is not empty. Some files may be replaced."))
  } else {
    stop(paste("Directory", output_files_dir, "does not exist. Create it before running the function."))
  }

  path_2_execs <- normalizePath(path_2_execs)

  # Inform parameters and directories set
  if(verbose){
    cat("Parameters set:\n",
        "  missing_value_code = -999\n",
        "  random_effect_col = 3\n",
        "  h2 = 0.5\n",
        "  num_runs = 5\n",
        "  num_folds = 10\n",
        "Directories:\n",
        "  input files:", input_files_dir, "\n",
        "  output files:", output_files_dir, "\n",
        "  executable files:", path_2_execs)
  }

  # define working directory
  wd_path <- base::getwd()

  #Assign .exes or not based on OS
  if (.Platform$OS.type == "unix") {
    predict = "predictf90"
    blup = "blupf90+"
  } else if (.Platform$OS.type == "windows") {
    predict = "predictf90.exe"
    blup = "blupf90+.exe"
  }

  # Run BF90 programs for the whole dataset
  setwd(input_files_dir)
  output <- execute_command(command = paste0(file.path(path_2_execs, blup)," ", "renf90.par"), logfile = "run_blup.log")
  command_predict <- paste0(file.path(path_2_execs, predict), " ", paste0("renf90.par"))
  output <- execute_command(command = command_predict, logfile = "run_predict.log")

  if (.Platform$OS.type == "unix") {
    system(paste0("mv run_blup.log bvs.dat bvs2.dat yhat_residual solutions ", output_files_dir))
  } else if (.Platform$OS.type == "windows") {
    files_res <- c("run_blup.log", "bvs.dat", "bvs2.dat", "yhat_residual", "solutions")
    for(i in 1:length(files_res)) shell(paste("MOVE ", files_res[i], output_files_dir))
  }

  # Prepare files for each BLUP run
  renf90 <- base::readLines(paste0("renf90.par"))
  #ped_file <- dirname(renf90_ped_name)
  fields_file <- base::readLines(paste0("renf90.fields"))
  inb_file <- base::readLines(paste0("renf90.inb"))
  tables_file <- base::readLines(paste0("renf90.tables"))

  # Read and preprocess the phenotype data
  bf90_phenos <- utils::read.table(paste0("renf90.dat"), sep = " ", header = FALSE) %>%
    dplyr::select(-1)

  # Shuffle the data and create folds
  data_shuffled <- base::lapply(1:num_runs, function(x) bf90_phenos[base::sample(base::nrow(bf90_phenos)), ] %>%
                                  dplyr::select((random_effect_col + 1)))

  folds <- base::lapply(data_shuffled, function(x) create_folds(x, num_folds))
  mutated_data <- base::lapply(folds, function(f) mutate_folds(bf90_phenos, f, num_folds,missing_value_code))

  setwd(output_files_dir)
  for (run in 1:num_runs) {
    for (fold in 1:num_folds) {
      dir_path <- base::sprintf("run%d/fold%d", run, fold)
      create_cv_datasets(run, fold, mutated_data[[run]][[fold]],
                         dir_path, renf90, renf90_ped_name,
                         input_files_dir, snp_file_name)
    }
  }

  # Run BLUPf90+ for each fold and collect EBVs
  ebvs_for_cv_runs <- base::list()
  for (run in 1:num_runs) {
    ebvs_for_cv_list <- base::list()
    for (fold in 1:num_folds) {
      base::setwd(base::file.path(output_files_dir, base::sprintf("run%d/fold%d", run, fold)))
      command <- base::paste0(file.path(path_2_execs, blup), base::sprintf(" renf90_run%d_fold%d.par", run, fold))
      logfile <- base::sprintf("blup_fold%d_run%d.log", fold, run)
      execute_command(command = command, logfile = logfile)

      data_file <- base::sprintf("renf90_run%d_fold%d.dat", run, fold)
      masked_ids <- utils::read.table(data_file) %>%
        dplyr::filter(V1 == missing_value_code) %>%
        dplyr::select(4) %>%
        base::unlist()

      ebvs_for_cv <- utils::read.table("solutions", header = FALSE, skip = 1) %>%
        dplyr::filter(V2 == random_effect_col & V3 %in% masked_ids) %>%
        dplyr::select(3, 4)

      ebvs_for_cv_list[[fold]] <- ebvs_for_cv
      utils::write.table(ebvs_for_cv, file = base::sprintf("ebvs_for_cv_run%d_fold%d.dat", run, fold), row.names = FALSE, col.names = TRUE, quote = FALSE)

    }
    ebvs_for_cv_runs[[base::sprintf("ebvs_for_cv_run%d", run)]] <- base::do.call(base::rbind, ebvs_for_cv_list)
  }
  base::setwd(output_files_dir)

  # Calculate correlations and bias
  corrected_phenos <- utils::read.table(paste0(output_files_dir,"/yhat_residual"), header = FALSE) %>% dplyr::select(1, 2)
  raw_phenos <- utils::read.table(paste0(input_files_dir,"/renf90.dat")) %>% dplyr::select(4, 1)

  ystar_correlations <- base::numeric(num_runs)
  yraw_correlations <- base::numeric(num_runs)
  yraw_list <- base::vector("list", num_runs)
  coefficients_list <- base::vector("list", num_runs)
  bias_list <- base::numeric(num_runs)

  for (i in 1:num_runs) {
    ystar <- dplyr::inner_join(ebvs_for_cv_runs[[base::sprintf("ebvs_for_cv_run%d", i)]], corrected_phenos, by = c("V3" = "V1"))
    ystar_correlations[i] <- stats::cor(ystar$V4, ystar$V2)

    yraw <- dplyr::inner_join(ebvs_for_cv_runs[[base::sprintf("ebvs_for_cv_run%d", i)]], raw_phenos, by = c("V3" = "V4"))
    yraw_correlations[i] <- stats::cor(yraw$V4, yraw$V1)
    yraw_list[[i]] <- yraw

    model <- stats::lm(V1 ~ V4, data = yraw_list[[i]])
    coefficients_list[[i]] <- stats::coefficients(model)
    bias_list[i] <- stats::coefficients(model)["V4"]
  }

  ystar_accuracy <- base::round(base::mean(ystar_correlations), 3)
  yraw_average_corr <- base::round(base::mean(yraw_correlations), 3)
  yraw_accuracy <- base::round(yraw_average_corr / base::sqrt(h2), 3)
  average_bias <- base::round(base::mean(bias_list), 3)

  data <- base::data.frame(
    Metric = base::c(base::rep("y-ebv_correlations", num_runs), base::rep("y*-ebv_correlations", num_runs), base::rep("bias", num_runs), "y-ebv_average_corr", "y*-ebv_accuracy", "y_corrected_accuracy (yraw_average_corr/sqrt(h2)", "average_bias"),
    Run = base::c(base::paste("run", 1:num_runs), base::paste("run", 1:num_runs), base::paste("run", 1:num_runs), "", "", "", ""),
    Value = base::round(base::c(yraw_correlations, ystar_correlations, bias_list, yraw_average_corr, ystar_accuracy, yraw_accuracy, average_bias), 3)
  )
  if(verbose) base::print (base::paste0("****Accuracy and bias table****" ))

  utils::write.table(data, file = output_table_name, row.names = FALSE, quote = FALSE)

  if(verbose) base::print(data)
  setwd(wd_path)
}
