#' Run postgibbsf90
#'
#' This function runs postgibbsf90 using the renf90.par file used to run gibbsf90+
#'
#' This function runs postgibbsf90 to provide diagnostic statistics,posterior means and standard deviations for analyses performed through gibbsf90+.
#' This function is written to run using the same renf90.par file used with run_gibbs and its output files are be the standard output files produced by postgibbsf90.
#' The user will have to enter the number of samples to burn and the number used to thin samples. A log file called run_postgibbs.log is also produced.
#'
#' @param path_2_execs path to a folder that holds the renumf90 executable. This field should be in quotes "".
#' @param input_files_dir path to renf90.par file generated by run_renum function
#' @param output_files_dir path to store the result files
#' @param postgibbs_burn number of samples to be discarded at the begining of the Gibbs sampler
#' @param postgibbs_keep the interval to save samples (thinning). Entering a 1 means all samples are kept.#'
#' @param verbose logical if TRUE prints log information in the console
#' 
#' @examples
#' ## Example
#'
#' # run_postgibbs( path_2_execs = "/Users/johndoe/Desktop/bf90_execs/",
#' # postgibbs_burn =1,
#' # postgibbs_keep = 100)
#'
#' @export
run_postgibbs <- function(path_2_execs, 
                          input_files_dir = ".",
                          output_files_dir = input_files_dir,
                          postgibbs_burn, 
                          postgibbs_keep, 
                          verbose = TRUE) {
  
  # Checks
  if(file.exists(output_files_dir)){
    check_files <- list.files(output_files_dir)
    output_files_dir <- normalizePath(output_files_dir)
  } else {
    stop(paste("Directory", output_files_dir, "does not exist. Create it before running the function."))
  }
  
  output_files_dir <- normalizePath(output_files_dir)
  input_files_dir <- normalizePath(input_files_dir)
  cur_dir <- getwd()
  
  #Assign .exe or not based on OS
  if (.Platform$OS.type == "unix") {
    postgibbs = "postgibbsf90"
  } else if (.Platform$OS.type == "windows") {
    postgibbs = "postgibbsf90.exe"
  }
  postgibbs_exec <- file.path(path_2_execs, postgibbs)

  # Check if executable exists
  if (!file.exists(postgibbs_exec)) {
    stop("Executable not found at: ", postgibbs_exec)
  }
  if (!file.exists(file.path(input_files_dir, "renf90.par"))) {
    stop("Parameter file not found: renf90.par")
  }

  # Create a temporary file with the inputs
  temp_input_file <- tempfile()
  writeLines(c(file.path(input_files_dir, "renf90.par"), postgibbs_burn, postgibbs_keep, "0"), temp_input_file)

  # Construct the command to use the input file
  if (.Platform$OS.type == "unix") {
    command_postgibbs <- paste0("cat ", temp_input_file, " | ", postgibbs_exec)
  } else if (.Platform$OS.type == "windows") {
    command_postgibbs <- paste0("type ", temp_input_file, " | \"", postgibbs_exec, "\"")
  }

  # Debugging: Print the constructed command
  if(verbose) cat("Running command:", command_postgibbs, "\n")

  # Run the command and log the output
  setwd(input_files_dir)
  output <- execute_command(command = command_postgibbs, logfile = "run_postgibbs.log")

  # Remove the temporary file
  unlink(temp_input_file)

  # Debugging: Print the output
  if(verbose) cat("Command output:", output, "\n")

  # Capture and print the log file content
  if(verbose){
    if (file.exists("run_postgibbs.log")) {
      cat("Log file content:\n")
      cat(readLines("run_postgibbs.log"), sep = "\n")
    } else {
      cat("Log file not created.\n")
    }
  }
  setwd(cur_dir)
}
