#' Run gibbsf90+
#'
#' This function runs gibbsf90+.
#'
#' This function runs gibbsf90+ using input from the user and a renf90.par file.
#' This function is written to use a renf90.par paramererfile, therefore the function run_renumf90 needs to be used beforehand to process a .par file created by the user.
#' The user will have to enter the number of samples in the MCMC chain, the number of samples to burn and the number used to thin samples. A log file called run_gibbs.log is also produced.
#' gibbsf90+ fits mixed threshold-linear models: categorical (ordinal) traits are declared with \code{OPTION cat}
#' (one value per trait, 0 for continuous; e.g. \code{options = "cat 4"} in write_par) and analysed on the
#' underlying liability scale, so a separate threshold program is not needed. With \code{OPTION solution mean}
#' gibbsf90+ also writes posterior-mean solutions to \code{final_solutions}, which this function moves alongside
#' the sample files when present.
#'
#' @param path_2_execs path to a folder that holds the renumf90 executable. This field should be in quotes "".
#' @param input_files_dir path to renf90.par file generated by run_renum function
#' @param output_files_dir path to store the result files
#' @param gibbs_iter number of samples in the Gibbs sampler.
#' @param gibbs_burn number of samples to be discarded at the begining of the Gibbs sampler
#' @param gibbs_keep the interval to save samples (thinning). Entering a 1 means all samples are kept.
#' @param verbose logical if TRUE prints log information
#'
#' @return No return value, called for side effects: runs gibbsf90+, producing the MCMC posterior-sample files (e.g. last_solutions, gibbs_samples, fort.99, and final_solutions when OPTION solution/fixed_var is used) and the run_gibbs.log log file.
#'
#' @examples
#' \dontrun{
#' run_gibbs(path_2_execs = "/path/to/bf90_execs/",
#'           gibbs_iter = 250000,
#'           gibbs_burn = 20000,
#'           gibbs_keep = 1)
#' }
#'
#' @export
run_gibbs <- function(path_2_execs,
                      input_files_dir = ".",
                      output_files_dir = input_files_dir,
                      gibbs_iter = 250000,
                      gibbs_burn = 20000,
                      gibbs_keep = 1,
                      verbose = TRUE) {

  if(input_files_dir != output_files_dir) warning("Next steps will required renum and gibbs results stored in same directory.")

  # Checks
  if(file.exists(output_files_dir)){
    check_files <- list.files(output_files_dir)
    output_files_dir <- normalizePath(output_files_dir)
  } else {
    stop(paste("Directory", output_files_dir, "does not exist. Create it before running the function."))
  }

  path_2_execs <- normalizePath(path_2_execs)
  cur_dir <- getwd()
  on.exit(setwd(cur_dir), add = TRUE)   # restore working dir even on error

  #Assign .exe or not based on OS
  if (.Platform$OS.type == "unix") {
    gibbs = "gibbsf90+"
  } else if (.Platform$OS.type == "windows") {
    gibbs = "gibbsf90+.exe"
  }
  gibbs_exec <- file.path(path_2_execs, gibbs)

  # Check if executable exists
  if (!file.exists(gibbs_exec)) {
    stop("Executable not found at: ", gibbs_exec)
  }

  if (!file.exists(file.path(input_files_dir, "renf90.par"))) {
    stop("Parameter file not found: renf90.par")
  }

  input_files_dir <- normalizePath(input_files_dir)

  # Create a temporary file with the inputs
  temp_input_file <- tempfile()
  writeLines(c(file.path(input_files_dir,"renf90.par"), gibbs_iter, gibbs_burn, gibbs_keep), temp_input_file)

  # Construct the command to use the input file
  if (.Platform$OS.type == "unix") {
    command_gibbs <- paste0("cat ", temp_input_file, " | ", gibbs_exec)
  } else if (.Platform$OS.type == "windows") {
    command_gibbs <- paste0("type ", temp_input_file, " | \"", gibbs_exec, "\"")
  }

  # Debugging: Print the constructed command
  if(verbose) cat("Running command:", command_gibbs, "\n")

  # Run the command and log the output
  setwd(input_files_dir)
  output <- execute_command(command = command_gibbs, logfile = "run_gibbs.log")
  if(output_files_dir != input_files_dir){
    # final_solutions is written by gibbsf90+ with OPTION solution/fixed_var; the rest are the usual sample files
    files_res <- c("last_solutions", "binary_final_solutions", "final_solutions", "fort.99", "gibbs_samples", "run_gibbs.log")
    for(i in seq_along(files_res)) if(file.exists(files_res[i])) file.rename(from = files_res[i], to = file.path(output_files_dir,files_res[i]))
  }

  # Remove the temporary file
  unlink(temp_input_file)

  # Debugging: Print the output
  if(verbose) cat("Command output:", output, "\n")

  # Capture and print the log file content
  if(verbose){
    if (file.exists(file.path(output_files_dir,"run_gibbs.log"))) {
      cat("Log file content:\n")
      cat(readLines(file.path(output_files_dir,"run_gibbs.log")), sep = "\n")
    } else {
      cat("Log file not created.\n")
    }
  }
  setwd(cur_dir)
}
